licensing/contributor_agreement_v01.md
Updated contributor agreement.
=> Type: Documentation

src/handlers/torrent.rs, src/tracker.rs
=> fix: fail torrent uploading when tracker whitelisting fails

migrations/mysql/20220727222313_torrust_tracker_keys.sql, migrations/sqlite3/20220727222313_torrust_tracker_keys.sql, src/databases/mysql.rs, src/databases/sqlite.rs, src/tracker.rs
=> fix: reuse valid tracker keys

Cargo.lock, Cargo.toml, compose.yaml, config-idx-back.toml.local, config-tracker.toml.local, project-words.txt, src/mailer.rs, src/routes/user.rs, tests/e2e/asserts.rs, tests/e2e/client.rs, tests/e2e/connection_info.rs, tests/e2e/contexts/about.rs, tests/e2e/contexts/category.rs, tests/e2e/contexts/mod.rs, tests/e2e/contexts/root.rs, tests/e2e/contexts/user.rs, tests/e2e/env.rs, tests/e2e/environment.rs, tests/e2e/http.rs, tests/e2e/mod.rs, tests/e2e/response.rs, tests/e2e/routes/about.rs, tests/e2e/routes/category.rs, tests/e2e/routes/mod.rs, tests/e2e/routes/root.rs
E2E tests for API `user` routes.
=> E2E tests for API `user` routes

src/routes/category.rs, tests/e2e/client.rs, tests/e2e/contexts/category.rs, tests/e2e/response.rs
Added more E2E tests for category routes.
=> More E2E tests for categories

docker/bin/e2e-env-restart.sh, src/routes/settings.rs, tests/e2e/client.rs, tests/e2e/contexts/mod.rs, tests/e2e/contexts/settings.rs, tests/e2e/contexts/user.rs, tests/e2e/mod.rs
E2E tests for API `settings` routes.
=> E2E tests for `settings` routes

config-idx-back.toml.local, config.toml.local, tests/common/contexts/settings/mod.rs, tests/e2e/contexts/settings/contract.rs, tests/e2e/environment.rs
Missing new image cache section in the configuration.
Issue: https://github.com/torrust/torrust-index-backend/issues/91
Failing test: https://github.com/torrust/torrust-index-backend/actions/runs/4882938414
=> Fix tests for issue 91

src/lib.rs, src/upgrades/from_v1_0_0_to_v2_0_0/upgrader.rs
Documentation for the command to upgrade the application.
=> App upgrader documentation

src/web/api/v1/contexts/proxy/handlers.rs, src/web/api/v1/contexts/proxy/mod.rs, src/web/api/v1/contexts/proxy/responses.rs, src/web/api/v1/contexts/proxy/routes.rs, src/web/api/v1/routes.rs, tests/e2e/contexts/mod.rs, tests/e2e/contexts/proxy/contract.rs, tests/e2e/contexts/proxy/mod.rs
API migration to Axum for `proxy` context.
=> Axum API: `proxy` context

src/databases/database.rs, src/databases/mysql.rs, src/databases/sqlite.rs, src/services/torrent.rs, src/tracker/service.rs, src/web/api/v1/contexts/torrent/forms.rs, src/web/api/v1/contexts/torrent/handlers.rs, src/web/api/v1/contexts/torrent/mod.rs, tests/common/contexts/torrent/forms.rs, tests/e2e/web/api/v1/contexts/torrent/contract.rs
Allow updating torrent category after upload.
=> Allow updating torrent category after upload

.github/workflows/codecov.yml, .github/workflows/publish_crate.yml, .github/workflows/test_docker.yml
Upload coverage report to [codecov](https://about.codecov.io/).
=> Upload coverage report to codecov

src/config.rs, src/databases/mysql.rs, src/databases/sqlite.rs, src/services/category.rs, src/services/tag.rs, src/web/api/v1/contexts/category/handlers.rs, src/web/api/v1/contexts/tag/handlers.rs, src/web/api/v1/contexts/user/handlers.rs, src/web/api/v1/routes.rs
Torrent files containing a lot of files (for example datasets) are big. In the future, this should be a config option.
=> Increase max request body size to 10MB

Cargo.lock, Cargo.toml, src/web/api/v1/routes.rs
**Modified:**
I have added the tower-http compression to the router.
One test fails, but this did not work before my changes.
=> #262: Add tower-http compression middleware

.github/CODEOWNERS, .github/dependabot.yaml, .github/labels.json, .github/workflows/labels.yaml, CODEOWNERS
Some basic workflow updates to match the torrust-tracker repo.
=> Workflow Updates

Cargo.lock
=> chore: bump serde_json to 1.0.108

contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh, contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
Stop containers running E2E tests when tests fail.
=> Stop containers running E2E tests when tests fail

contrib/dev-tools/init/install-local.sh
Add script to set up DB for development.
It'll be used in the Development Guide for the Index GUI: https://github.com/torrust/torrust-index-gui/pull/394
=> Add script to setup DB for development

tests/e2e/environment.rs
=> Fix clippy linting error #449

.github/workflows/coverage.yaml, .github/workflows/testing.yaml
Run coverage report only in coverage workflow.
=> Run coverage report only in coverage workflow

tests/common/contexts/torrent/file.rs, tests/common/contexts/torrent/fixtures.rs, tests/common/contexts/user/responses.rs
=> Fix project not building due to unused code

contrib/dev-tools/container/e2e/mysql/e2e-env-down.sh, contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh, contrib/dev-tools/container/e2e/sqlite/e2e-env-down.sh, contrib/dev-tools/container/e2e/sqlite/e2e-env-up.sh, contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh, contrib/dev-tools/init/install-local.sh
Fix errors in scripts:
- Wrong file paths
- Format scripts
=> Fix errors in scripts

src/config.rs
We will overhaul the configuration, so it's convenient to have some tests.
=> Add some tests to configuration before refactoring

Cargo.lock, Cargo.toml, src/app.rs, src/common.rs, src/services/authentication.rs, src/services/authorization.rs, src/services/category.rs, src/services/mod.rs, src/services/proxy.rs, src/services/settings.rs, src/services/tag.rs, src/services/torrent.rs, src/services/user.rs
=> 448 move authorization logic to new layer

share/default/config/tracker.private.e2e.container.sqlite3.toml, share/default/config/tracker.public.e2e.container.sqlite3.toml
Update tracker config. The Tracker toml config has introduced breaking changes.
=> Update tracker config

Containerfile, contrib/dev-tools/container/e2e/mysql/e2e-env-up.sh, contrib/dev-tools/container/e2e/sqlite/mode/private/e2e-env-up.sh, contrib/dev-tools/container/e2e/sqlite/mode/public/e2e-env-up.sh, share/default/config/tracker.private.e2e.container.sqlite3.toml, share/default/config/tracker.public.e2e.container.sqlite3.toml
Options for drivers use lowervcase now.
=> Update tracker database driver config

src/config/v2/registration.rs, src/services/authentication.rs, src/services/user.rs, tests/common/contexts/settings/mod.rs, tests/environments/isolated.rs
From:
```toml
[registration]
[registration.email]
required = true
verified = true
```
To:
```toml
[registration]
[registration.email]
required = true
verification_required = true
```
=> Rename email config option

share/default/config/tracker.private.e2e.container.sqlite3.toml, share/default/config/tracker.public.e2e.container.sqlite3.toml
Some config options are now mandatory.
=> Update tracker configuration 

src/app.rs
=> Remove debugging code

Cargo.lock, Cargo.toml
Version 3.0.0-rc.1 was Released
=> Version 3.0.0-rc.1 was Released

tests/e2e/web/api/v1/contexts/torrent/contract.rs
=> Authorization tests for the torrent context

src/lib.rs, src/services/authorization.rs
Fix the command to run the index from sources after compilation.
=> Docs: fix command
