torrust/torrust-index

- Cargo.lock
- Cargo.toml
- src/errors.rs
- src/handlers/user.rs
- src/utils/mod.rs
- src/utils/regex.rs
> fix: verify email address validity on signup

- src/config.rs
- src/databases/database.rs
- src/errors.rs
- src/main.rs
- tests/databases/mod.rs
- tests/databases/mysql.rs
- tests/databases/sqlite.rs
> feat: auto detect `db_driver` from `connect_url`

- src/databases/mysql.rs
- src/databases/sqlite.rs
> fix: [#79] prioritize `announce-list` over `announce`

- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/routes/torrent.rs
- src/tracker.rs
When a new torrent is uploaded, we must update the tracker torrent stats in the `torrust_torrent_tracker_stats` table.
It worked from the UI but not for the [DB migration script](https://github.com/torrust/torrust-index-backend/pull/77) because the frontend makes a request to get the torrent info after the upload, and that endpoint updates the torrent tracker stats.
It must update the stats even if that endpoint is not called after uploading a new torrent.
- Extract `TrackerApiClient` from `TrackerService`
- Rename `TrackerService::get_torrent_info` to `TrackerService::update_torrent_tracker_stats`
> Restore broken behavior: after uploading a new torrent its tracker stats must be updated

- src/tracker.rs
The tracker API uses now a prefix with the version. It has changed from:
http://0.0.0.0:1212/api/stats?token=MyAccessToken
to:
http://0.0.0.0:1212/api/v1/stats?token=MyAccessToken
> Add prefix `v1` to tracker API

- .vscode/extensions.json
- .vscode/settings.json
Same configuration as https://github.com/torrust/torrust-tracker.
It does not enforce it in CI because there are a lot of errors for Clippy in `pedantic` mode.
```
cargo clippy --all-targets -- -D clippy::pedantic
```
> Update Visual Studio Code config to follow Tracker conventions

- CODEOWNERS
@da2ce7 @josecelano @WarmBeer get notified when a PR changes the `.github` dir content.
@WarmBeer, we should also enable required reviews for PR and require approval from a code owner before the author can merge a pull request in the repository.
_"Optionally, you can choose to require reviews from code owners. If you do, any pull request that affects code with a code owner must be approved by that code owner before the pull request can be merged into the protected branch."_
See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-pull-request-reviews-before-merging
I don't have permission to do it.
> Add code owners for GitHub workflows

- tests/e2e/asserts.rs
- tests/e2e/client.rs
- tests/e2e/connection_info.rs
- tests/e2e/env.rs
- tests/e2e/mod.rs
- tests/e2e/routes/about.rs
- tests/e2e/routes/category.rs
- tests/e2e/routes/mod.rs
- tests/e2e/routes/root.rs
E2E tests for API `category` routes.
> E2E tests for API `category` routes

- Cargo.lock
- Cargo.toml
Fix dependabot alert [GHSA-wcg3-cvx6-7396](https://github.com/advisories/GHSA-wcg3-cvx6-7396).
> Fix dependabot alert GHSA-wcg3-cvx6-7396

- project-words.txt
- src/app.rs
- src/bin/main.rs
- src/bootstrap/config.rs
- src/bootstrap/logging.rs
- src/bootstrap/mod.rs
- src/config.rs
- src/console/commands/import_tracker_statistics.rs
- src/lib.rs
- src/routes/settings.rs
- src/tracker.rs
- tests/common/mod.rs
- tests/common/random.rs
- tests/integration/app_starter.rs
- tests/integration/contexts/about.rs
- tests/integration/environment.rs
- tests/integration/mod.rs
Changes needed to run tests with independent app instances running on different ports.
> Integration tests scaffolding

- .gitignore
- Cargo.lock
- Cargo.toml
- src/app.rs
- src/cache/cache.rs
- src/cache/image/manager.rs
- src/cache/image/mod.rs
- src/cache/mod.rs
- src/common.rs
- src/config.rs
- src/errors.rs
- src/lib.rs
- src/routes/mod.rs
- src/routes/proxy.rs
- src/tracker.rs
Rebased and processed @josecelano 's feedback: https://github.com/torrust/torrust-index-backend/pull/100
> feat: [#91] added image proxy with cache

- src/auth.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/mailer.rs
- src/routes/user.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
- src/utils/clock.rs
- src/utils/mod.rs
- src/utils/time.rs
It fixes this build warning:
```
warning: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp`: use `from_timestamp_opt()` instead
--> src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs:53:41
|
53 |     let naive_datetime = NaiveDateTime::from_timestamp(timestamp, 0);
|                                         ^^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
```
> Fix deprecate chrono function warning

- .dockerignore
- bin/install.sh
- config-idx-back.local.toml
- config.local.toml
- src/config.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/routes/settings.rs
- src/routes/torrent.rs
- tests/common/client.rs
- tests/common/contexts/settings/mod.rs
- tests/e2e/contexts/torrent/contract.rs
- tests/environments/app_starter.rs
- tests/environments/isolated.rs
Changes in GET torrents response pagination.
The minimum page size for GET torrents results was removed. You can request only one torrent.
**BREAKING CHANGE**: a maximum page size was added (30). If you request more than 30 torrents per page, the result will contain 30 torrents at the most.
> Change GET torrents page size limits

- src/bootstrap/config.rs
- src/config.rs
- src/routes/settings.rs
- tests/e2e/contexts/settings/contract.rs
- tests/environments/app_starter.rs
- tests/environments/isolated.rs
You can now overwrite the default config file path with:
```s
TORRUST_IDX_BACK_CONFIG_PATH=./storage/config/config.toml cargo run
```
The default path is `./config.toml`
> Add environment variable to change the default config file path `./config.toml`

- .github/workflows/develop.yml
- src/app.rs
- src/bootstrap/config.rs
- src/config.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/mailer.rs
- src/routes/user.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/databases/mod.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/transferrers/category_transferrer.rs
- tests/e2e/config.rs
- tests/e2e/contexts/torrent/asserts.rs
- tests/e2e/contexts/torrent/contract.rs
- tests/e2e/contexts/torrent/steps.rs
- tests/upgrades/from_v1_0_0_to_v2_0_0/sqlite_v1_0_0.rs
- tests/upgrades/from_v1_0_0_to_v2_0_0/sqlite_v2_0_0.rs
> Enable pedantic clippy on CI

- config-idx-back.local.toml
- config.local.toml
- src/app.rs
- src/config.rs
- tests/common/contexts/settings/mod.rs
From `database` section to a new section:
```toml
[tracker_statistics_importer]
torrent_info_update_interval = 3600
```
It's a breaking change.
> Move config option `torrent_info_update_interval`

- .github/workflows/publish_crate.yml
- Cargo.lock
- Cargo.toml
Prepare new release: `2.0.0-alpha.1`
> Package release: `2.0.0-alpha.1`

- .github/workflows/publish_crate.yml
- .github/workflows/publish_docker_image.yml
- .github/workflows/release.yml
Unit tests have a dependency with the binary: `imdl`. It's used to create and parse torrents.
Before running tests with `cargo test` you have to install with: `cargo install imdl`.
> ci: install `imdl` binary in all workflows

- src/routes/about.rs
- src/routes/category.rs
- src/routes/mod.rs
- src/routes/proxy.rs
- src/routes/root.rs
- src/routes/settings.rs
- src/routes/torrent.rs
- src/routes/user.rs
- tests/common/client.rs
- tests/common/connection_info.rs
BREAKING CHANGE: API urls have the prefix `/v1/...`
> Add API version prefix in API URLs

- project-words.txt
- src/bin/import_tracker_statistics.rs
- src/config.rs
- src/console/commands/import_tracker_statistics.rs
- src/lib.rs
- src/services/about.rs
- src/services/authentication.rs
- src/services/mod.rs
- src/services/settings.rs
- src/services/torrent.rs
- src/services/user.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/upgrader.rs
Move installation and configuration docs to Rust [Documentation Comments](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#making-useful-documentation-comments).
> Installation and configurations docs

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/bin/main.rs
- src/bootstrap/logging.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/services/about.rs
- src/web/api/actix.rs
- src/web/api/axum.rs
- src/web/api/mod.rs
- src/web/api/v1/contexts/about/handlers.rs
- src/web/api/v1/contexts/about/mod.rs
- src/web/api/v1/contexts/about/routes.rs
- src/web/api/v1/mod.rs
- src/web/api/v1/routes.rs
- tests/e2e/contexts/about/contract.rs
- tests/e2e/contexts/category/contract.rs
- tests/e2e/contexts/root/contract.rs
- tests/e2e/contexts/settings/contract.rs
- tests/e2e/contexts/torrent/contract.rs
- tests/e2e/contexts/user/contract.rs
- tests/e2e/environment.rs
- tests/environments/app_starter.rs
- tests/environments/isolated.rs
Basic changes which are needed to run the Axum API implementation in parallel with the current one with ActixWeb. For the time being the Axum implementation will be only used for testing until all endpoints are migrated.
> Axum API scaffolding

- config-idx-back.local.toml
- config.local.toml
- src/app.rs
- src/bootstrap/logging.rs
- src/config.rs
- src/console/commands/import_tracker_statistics.rs
- tests/environments/isolated.rs
```toml
log_level = "info"
```
The level can be:
- `off`
- `error`
- `warn`
- `info`
- `debug`
- `trace`
It's optional. The default value is `info`.
> New config option for log level

- src/app.rs
- src/common.rs
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/errors.rs
- src/routes/tag.rs
- src/services/category.rs
- src/services/mod.rs
- src/services/tag.rs
- src/services/torrent.rs
- tests/common/client.rs
- tests/common/contexts/mod.rs
- tests/common/contexts/tag/fixtures.rs
- tests/common/contexts/tag/forms.rs
- tests/common/contexts/tag/mod.rs
- tests/common/contexts/tag/responses.rs
- tests/e2e/contexts/mod.rs
- tests/e2e/contexts/tag/contract.rs
- tests/e2e/contexts/tag/mod.rs
- tests/e2e/contexts/tag/steps.rs
A new API context was created, `tag`, but the code is in the ActixWeb handler. [We were migrating that code to services](https://github.com/torrust/torrust-index-backend/issues/157).
> Refactor API: extract `tag` service

- docker/bin/run-e2e-tests.sh
The workflow "Development checks" is not failing if E2E tests fail. This fixes that problem.
> Make `development checks` workflow fail if E2E test fails

- src/databases/sqlite.rs
The SQL query:
```sql
SELECT
COUNT(*) as count
FROM
(
SELECT
tt.torrent_id,
tp.username AS uploader,
tt.info_hash,
ti.title,
ti.description,
tt.category_id,
DATE_FORMAT(tt.date_uploaded, '%Y-%m-%d %H:%i:%s') AS date_uploaded,
tt.size AS file_size,
CAST(COALESCE(sum(ts.seeders), 0) as signed) as seeders,
CAST(COALESCE(sum(ts.leechers), 0) as signed) as leechers
FROM
torrust_torrents tt
INNER JOIN torrust_user_profiles tp ON tt.uploader_id = tp.user_id
INNER JOIN torrust_torrent_info ti ON tt.torrent_id = ti.torrent_id
LEFT JOIN torrust_torrent_tracker_stats ts ON tt.torrent_id = ts.torrent_id
WHERE
title LIKE ?
GROUP BY
tt.torrent_id
) AS count_table
```
should not use the `DATE_FORMAT` function in SQLite.
> Fix SQL error in SQLite

- src/web/api/v1/contexts/category/forms.rs
- src/web/api/v1/contexts/category/handlers.rs
- src/web/api/v1/contexts/category/mod.rs
- src/web/api/v1/contexts/category/responses.rs
- src/web/api/v1/contexts/category/routes.rs
- src/web/api/v1/routes.rs
- tests/common/contexts/category/asserts.rs
- tests/common/contexts/category/mod.rs
- tests/common/contexts/category/responses.rs
- tests/e2e/contexts/category/contract.rs
- tests/e2e/contexts/category/steps.rs
- tests/e2e/contexts/user/steps.rs
API migration to Axum for `category` context.
> Axum API: `category` context

- src/web/api/v1/routes.rs
- tests/e2e/contexts/root/contract.rs
API migration to Axum for root endpoints.
> Axum API: `root` enpoints

- src/web/api/v1/contexts/mod.rs
- src/web/api/v1/contexts/tag/forms.rs
- src/web/api/v1/contexts/tag/handlers.rs
- src/web/api/v1/contexts/tag/mod.rs
- src/web/api/v1/contexts/tag/responses.rs
- src/web/api/v1/contexts/tag/routes.rs
- src/web/api/v1/routes.rs
- tests/common/contexts/tag/asserts.rs
- tests/common/contexts/tag/mod.rs
- tests/common/contexts/tag/responses.rs
- tests/e2e/contexts/tag/contract.rs
API migration to Axum for `tag` context.
> Axum API: `tag` context

- src/web/api/v1/contexts/settings/handlers.rs
- src/web/api/v1/contexts/settings/mod.rs
- src/web/api/v1/contexts/settings/routes.rs
- src/web/api/v1/routes.rs
- tests/e2e/contexts/settings/contract.rs
API migration to Axum for `settings` context.
> Axum API: `settings` context

- Cargo.lock
- Cargo.toml
- src/auth.rs
- src/errors.rs
- src/web/api/v1/contexts/category/handlers.rs
- src/web/api/v1/contexts/category/responses.rs
- src/web/api/v1/contexts/settings/handlers.rs
- src/web/api/v1/contexts/tag/handlers.rs
- src/web/api/v1/contexts/tag/responses.rs
- src/web/api/v1/contexts/torrent/forms.rs
- src/web/api/v1/contexts/torrent/handlers.rs
- src/web/api/v1/contexts/torrent/mod.rs
- src/web/api/v1/contexts/torrent/responses.rs
- src/web/api/v1/contexts/torrent/routes.rs
- src/web/api/v1/contexts/user/handlers.rs
- src/web/api/v1/contexts/user/responses.rs
- src/web/api/v1/responses.rs
- src/web/api/v1/routes.rs
- tests/common/asserts.rs
- tests/common/contexts/category/asserts.rs
- tests/common/contexts/tag/asserts.rs
- tests/common/contexts/user/asserts.rs
- tests/e2e/contexts/category/contract.rs
- tests/e2e/contexts/settings/contract.rs
- tests/e2e/contexts/tag/contract.rs
- tests/e2e/contexts/torrent/contract.rs
API migration to Axum for `torrent` context.
Torrent files:
Indexed torrents:
> Axum API: `torrent` context

- .github/workflows/develop.yml
- src/bin/main.rs
- tests/e2e/config.rs
- tests/e2e/contexts/about/contract.rs
- tests/e2e/contexts/category/contract.rs
- tests/e2e/contexts/root/contract.rs
- tests/e2e/contexts/settings/contract.rs
- tests/e2e/contexts/tag/contract.rs
- tests/e2e/contexts/torrent/contract.rs
- tests/e2e/contexts/user/contract.rs
This makes the Axum implementation the default one for the API.
> Axum API: make it the default implementation

- src/bootstrap/config.rs
- src/web/api/v1/routes.rs
Running the backend with:
```
TORRUST_IDX_BACK_CORS_PERMISSIVE=true cargo run
```
will make the CORS policy to be permissive, which means you can use a different port for the API and serving the frontend app. It's intented for development purposes.
> Add environment variable to set permissive CORS policy

- src/errors.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
The [endpoint to get the torrent info details](https://github.com/torrust/torrust-index-backend/blob/develop/src/web/api/v1/contexts/torrent/handlers.rs#L112-L128) returns a `404` HTTP status code instead of a `400` when the provided infohash does not exist in the database.
The [endpoint to download the torrent file](https://github.com/torrust/torrust-index-backend/blob/develop/src/web/api/v1/contexts/torrent/handlers.rs#L66-L86) is also changed.
> Return 404 when torrent is not found

- migrations/mysql/20230627103405_torrust_allow_null_categories.sql
- migrations/sqlite3/20230627103405_torrust_allow_null_categories.sql
- src/models/response.rs
- src/models/torrent.rs
- src/services/torrent.rs
The JSON response can now contain a `null` value for the `category`:
```json
{
"data": {
"torrent_id": 1,
"uploader": "josecelano",
"info_hash": "E8564469C258B1373BC2D5749FB83B1BF83D68A0",
"title": "Ubuntu",
"description": null,
"category": null,
"upload_date": "2023-06-27 11:35:09",
"file_size": 1261707713,
"seeders": 0,
"leechers": 0,
"files": [
{
"path": [
"NNN.url"
],
"length": 114,
"md5sum": null
},
{
"path": [
"XXX.url"
],
"length": 121,
"md5sum": null
},
{
"path": [
"XXX.avi"
],
"length": 1261707478,
"md5sum": null
}
],
"trackers": [
"udp://tracker:6969",
],
"magnet_link": "magnet:?xt=urn:btih:E8564469C258B1373BC2D5749FB83B1BF83D68A0&dn=Ubuntu&tr=udp%3A%2F%2Ftracker%3A6969e",
"tags": []
}
}
```
> Make torrent category optional

- migrations/mysql/20230627144318_torrust_covert_infohashes_to_lowercase.sql
- migrations/sqlite3/20230627144318_torrust_covert_infohashes_to_lowercase.sql
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/models/torrent_file.rs
- src/web/api/v1/contexts/torrent/handlers.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
[We decided to use lowercase infohashes](https://github.com/torrust/torrust-index-backend/blob/develop/adrs/20230510152112_lowercas_infohashes.md).
> Lowercase infohashes

- src/errors.rs
- src/services/torrent.rs
- Torrent title is checked that the title has at least 3 characters
- If the title is smaller, a service error is issued
> Add minimum length in Torrent Title

- Cargo.lock
- Cargo.toml
- src/models/info_hash.rs
- src/models/torrent_file.rs
- src/services/hasher.rs
- src/services/mod.rs
- src/services/torrent_file.rs
- src/web/api/v1/contexts/torrent/handlers.rs
- src/web/api/v1/contexts/torrent/responses.rs
- src/web/api/v1/contexts/torrent/routes.rs
Relates to: https://github.com/torrust/torrust-index-frontend/pull/185
Sometimes we need to generate a random torrent for testing purposes.
We need to generate test torrents for the frontend application. With this new endpoint, you can get a random torrent:
http://0.0.0.0:3001/v1/torrents/random
The torrent is a single-file torrent using a UUID for its name and the original data file contents.
In this repo, we use the `imdl` command to generate random torrents but in the frontend we are using cypress, and it seems the best option is [to make a request to an endpoint](https://docs.cypress.io/api/commands/request) to obtain dynamic fixtures like random (or customized in the future) torrents.
https://github.com/torrust/torrust-index-frontend/pull/185
Other things that we could implement:
> Endpoint to create random torrents

- src/services/torrent.rs
- src/web/api/v1/contexts/torrent/handlers.rs
- src/web/api/v1/contexts/torrent/responses.rs
Endpoints, where you can download a torrent file, have now a custom header containing the torrent infohash. The name of the header is: `x-torrust-torrent-infohash`.
It is added because [in the frontend we need the infohash in a cypress test](https://github.com/torrust/torrust-index-frontend/pull/185) and this way we do not need to parse the downloaded torrent which is faster and simpler.
> Add a custom header with info-hash to the download endpoints

- src/errors.rs
- src/models/torrent.rs
- src/models/torrent_file.rs
- src/services/torrent.rs
- src/web/api/v1/contexts/torrent/errors.rs
- src/web/api/v1/contexts/torrent/handlers.rs
- src/web/api/v1/contexts/torrent/mod.rs
- src/web/api/v1/responses.rs
Add a custom error for each case so that the Bad Request response constains a descriptive error message.
> Improve `Bad Request` error message for uploading

- bin/install.sh
- docker/bin/e2e/sqlite/e2e-env-reset.sh
I forgot some changes in the previous [PR](https://github.com/torrust/torrust-index-backend/pull/270).
> Clean sqlite bash commands

- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/models/response.rs
- src/models/torrent.rs
- tests/common/contexts/torrent/fixtures.rs
- tests/common/contexts/torrent/responses.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
> Add torrent `name` to  torrent list an detail endpoints

- .github/workflows/coverage.yaml
- .github/workflows/testing.yaml
- migrations/mysql/20230905091837_torrust_multiple_original_infohashes.sql
- migrations/sqlite3/20230905091837_torrust_multiple_original_infohashes.sql
- src/app.rs
- src/common.rs
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/errors.rs
- src/lib.rs
- src/models/torrent_file.rs
- src/services/torrent.rs
- src/tracker/service.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
- src/utils/parse_torrent.rs
- src/web/api/mod.rs
- src/web/api/v1/contexts/torrent/handlers.rs
- src/web/api/v1/contexts/torrent/mod.rs
- src/web/api/v1/mod.rs
- tests/common/contexts/torrent/file.rs
- tests/common/contexts/torrent/fixtures.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
When you upload a torrent, the infohash might change if the `info` dictionary contains non-standard fields because we remove them. That leads to a different infohash. We store the 
original infohash in a new table so that we can know if the torrent was previously uploaded.
If we do not store the original infohash we could reject uploads producing the same canonical infohash. Still, there is no way for the user to ask if a torrent exists with a given original infohash. They only would be able to interact with the API with the canonical infohash.
Sometimes it's useful to use the original infohash, for instance, if you are importing torrents from an external source and you want to check if the original torrent (with the original infohash) was already uploaded.
> feat: [#261] store original info-hashes

- .github/workflows/testing.yaml
This should make integration tests faster as we can mount the rust dependencies cache inside the container.
> Enable rust cache for integration tests

- src/app.rs
- src/common.rs
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/services/torrent.rs
- src/web/api/v1/contexts/torrent/handlers.rs
- tests/common/client.rs
- tests/common/contexts/torrent/fixtures.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
- tests/e2e/web/api/v1/contexts/torrent/steps.rs
For endpoints using a GET param with an infohash:
- `GET /v1/torrent/INFO_HASH`
- `GET /v1/torrent/download/INFO_HASH`
That param must be the canonical infohash so far. This PR allows users to use the original info-hash.
Suppose the URL contains an info-hash, which is not canonical but belongs to a canonical info-hash group. In that case, the response will be a redirection (307) to the same URL but using the canonical info-hash.
> Redirect to URL with canonical info-hash

- src/errors.rs
- src/services/category.rs
- tests/e2e/web/api/v1/contexts/category/contract.rs
It was allowed to use an empty string like "" or " " for a category name.
From now on, it's not allowed.
If there were some empty names in the database, they were not renamed. Admins must optionally do that. Names were anyway UNIQUE.
A migration to rename empty names was not added because there can be more than one category, for example:
- ""
- " "
- "  "
- Etcetera
We could have generated names like "no category 1", "no category 2", but it's not likely that admins have created empty categories.
> Do not allow empty category names

- migrations/mysql/20230914155441_torrust_no_duplicate_tags.sql
- migrations/sqlite3/20230914155441_torrust_no_duplicate_tags.sql
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/errors.rs
- src/services/tag.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
- src/web/api/v1/contexts/tag/handlers.rs
- tests/e2e/web/api/v1/contexts/tag/contract.rs
- tests/e2e/web/api/v1/contexts/user/steps.rs
It was allowed to use empty strings like "" or " " for a tag name.
After merging this PR, it will not be allowed anymore.
If there are some empty names in the database, they are not renamed.
A migration to rename empty names was not added because there can be more than one tag, for example:
- ""
- " "
- "  "
- Etcetera
We could have generated names like "no tag 1", "no tag 2", but it's not likely that admins have created empty tags.
It was allowed to use empty strings like "" or " " for a tag name. And It was also allowed to have duplicate tags.
After merging this PR, it will not be allowed anymore.
If there are duplicate tag names, the duplication is removed by appending the tag id as a suffix to the tag name.
> Do not allow empty or duplicate tag names

- migrations/mysql/20230918103654_torrust_add_comment_field_to_torrent.sql
- migrations/sqlite3/20230918103654_torrust_add_comment_field_to_torrent.sql
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/models/response.rs
- src/models/torrent.rs
- src/models/torrent_file.rs
- src/services/torrent.rs
- src/services/torrent_file.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
- tests/common/contexts/tag/fixtures.rs
- tests/common/contexts/torrent/responses.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
And add it to the API responses.
- Torrent details endpoint
- Torrent list endpoint
- Include the `comment` in the downloaded torrent
> Persist torrent `comment`

- Cargo.lock
- Cargo.toml
- src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
- Update dependencies: `cargo update`
- Removed unused dependencies: `actix-web`, `actix-multipart`, `actix-cors`. The [API was migrated to Auxm](https://github.com/torrust/torrust-index-backend/issues/156), but [the dependency was not removed](https://github.com/torrust/torrust-index-backend/issues/208).
> Review dependencies

- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/errors.rs
- src/models/torrent.rs
- src/models/torrent_file.rs
- src/services/torrent.rs
- src/utils/parse_torrent.rs
- src/web/api/v1/contexts/torrent/handlers.rs
- tests/common/client.rs
- tests/common/contexts/torrent/fixtures.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
> Refactor: the function `services::torrent::Index::add_torrent`

- Cargo.lock
- src/models/torrent_file.rs
Using our crate `torrust-serde-bencode` instead of the upstream repo fixes the problem with some torrent deserializations described in this [issue](https://github.com/torrust/torrust-index/issues/266).
There was a problem with lists (field `nodes` in the torrent) containing other lists (tuples) with different value types.
```json
{
"info": {
"length": 8,
"name": "minimal.txt",
"piece length": 16384,
"pieces": "<hex>30 9A 84 51 4A F1 09 D0 8C 34 42 11 26 67 7F 84 B3 23 4D 78</hex>"
},
"nodes": [
[
"188.163.121.224",
56711
],
[
"162.250.131.26",
13386
]
]
}
```
I have been trying to reproduce the bug in our fork [here](https://github.com/torrust/torrust-serde-bencode/issues/12), but it works. I've added a test using the same torrent file that does not work here.
If you run:
```console
cargo …
```
> User forked version of `serde-bencode`

- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/errors.rs
- src/services/category.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
Hello !
This PR fixes [#253](https://github.com/torrust/torrust-index/issues/253).
I think that we can keep the unique constraint in the DB on top of this change as proposed by @josecelano in the original issue
Following this change, I think that we should move some of the error logic that is inside the databases crate to the services one.
All of these errors should not be raised at database level but rather at the service level:
- `database::Error::UsernameTaken`
- `database::Error::EmailTaken`
- `database::Error::TagAlreadyExists`
- `database::Error::TorrentAlreadyExists`
- `database::Error::TorrentTitleAlreadyExists`
This will permit to avoid using database error message parsing which is implementation specific and error prone (like …
> fix: rework error handling for add_category

- .dockerignore
- .github/workflows/testing.yaml
- compose.yaml
- contrib/dev-tools/container/e2e/mysql/e2e-env-down.sh
- contrib/dev-tools/container/e2e/mysql/e2e-env-reset.sh
- contrib/dev-tools/container/e2e/mysql/e2e-env-restart.sh
- contrib/dev-tools/container/e2e/mysql/e2e-env-up.sh
- contrib/dev-tools/container/e2e/run-e2e-tests.sh
- contrib/dev-tools/container/e2e/sqlite/e2e-env-down.sh
- contrib/dev-tools/container/e2e/sqlite/e2e-env-reset.sh
- contrib/dev-tools/container/e2e/sqlite/e2e-env-restart.sh
- contrib/dev-tools/container/e2e/sqlite/e2e-env-up.sh
- contrib/dev-tools/container/install.sh
- contrib/dev-tools/init/install-local.sh
> Reestablish E2E Tests

- .github/workflows/container.yaml
From: `torrust/index-backend:develop`
To: `torrust/index:develop`
> Use normal variables instead of secrets for `user` and `repo` on DockerHub

- contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
- contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
- contrib/dev-tools/container/functions/wait_for_container_to_be_healthy.sh
Extract duplicate function `wait_for_container_to_be_healthy` in E2E test scripts.
> Refactor: extract duplicate function `wait_for_container_to_be_healthy`

- Containerfile
- contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
- contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
- share/default/config/index.container.mysql.toml
- share/default/config/index.container.sqlite3.toml
- share/default/config/index.development.sqlite3.toml
- src/app.rs
- src/bin/health_check.rs
- src/config.rs
- src/console/mod.rs
- src/console/tracker_statistics_importer.rs
- src/lib.rs
- src/web/api/v1/contexts/settings/mod.rs
- src/web/api/v1/routes.rs
- tests/common/contexts/settings/mod.rs
- tests/environments/isolated.rs
[After discussing how to implement a proper container HEALTHCHECK for the Index ](https://github.com/torrust/torrust-index/issues/254) this final implementation:
- Doesn't use `curl`, `wget` or other system dependency to [avoid maintaining that dependency and security attacks](https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/). It uses a new binary that you can use like this: `cargo run --bin health_check http://localhost:PORT/health_check`.
- Adds an API to the tracker statistics importer so that other processes can communicate with the cronjob.
- Exposes a `/health_check` endpoint in both APIs: the Index API and the Importer API (console cronjob).
- The endpoint for the Index core API is public but the one for the cronjob it runs only on the localhost.
You can run …
> Implement health check for the Index container

- contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
- contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
- tests/e2e/config.rs
- tests/e2e/environment.rs
How to run E2E tests example:
```bash
TORRUST_INDEX_E2E_SHARED=true \
TORRUST_INDEX_E2E_PATH_CONFIG="./share/default/config/index.e2e.container.mysql.toml" \
TORRUST_INDEX_E2E_DB_CONNECT_URL="mysql://root:root_secret_password@localhost:3306/torrust_index_e2e_testing" \
cargo test \
|| exit 1
```
The new `TORRUST_INDEX_E2E_DB_CONNECT_URL` is used to connect to the E2E DB directly. IT's needed for some tests to set the initial state needed for the test, when it's not possible do do it otherwise.
> Inject E2E DB connection info with environent  variable

- contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
- contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
- share/default/config/tracker.container.mysql.toml
- share/default/config/tracker.container.sqlite3.toml
- share/default/config/tracker.e2e.container.sqlite3.toml
Instead of just waiting 20 seconds. Now the Tracker container has `HEALTHCHECK` instruction.
See: https://github.com/torrust/torrust-tracker/issues/508
> Wait for Tracker container to be healthy

- src/databases/mysql.rs
- src/databases/sqlite.rs
- SQL statements are only logged when the global logging level is `Debug`.
- Slow SQL statements are only logged when the global logging level is `Info`.
> Change logging level for SQL statements

- src/tracker/api.rs
- src/tracker/service.rs
When the API token contains special characters like: `123g7#@agJtWFSgkdA5R$K22yeo$k6IhNq%T2$r`
The value must be URL-encoded like this:
http://tracker.torrust-demo.com:1212/v1/stats?token=123g7%23%40agJtWFSgkdA5R%24K22yeo%24k6IhNq%25T2%24r
Instead of using the token directly:
http://tracker.torrust-demo.com:1212/v1/stats?token=123g7#@agJtWFSgkdA5R$K22yeo$k6IhNq%T2$r
This PR also fixes the issue https://github.com/torrust/torrust-index/issues/391
> Encode tracker API token in  HTTP requests

- src/errors.rs
- src/services/torrent.rs
- src/tracker/service.rs
- src/tracker/statistics_importer.rs
- tests/common/contexts/torrent/responses.rs
We need the specific error requesting the tracker API to include the error in the logs.
> Improve Tracker API errors log

- .github/workflows/coverage.yaml
- Cargo.lock
```console
$ cargo update zerocopy
Updating crates.io index
Updating zerocopy v0.7.25 -> v0.7.32
Updating zerocopy-derive v0.7.25 -> v0.7.32
$ cargo update config
Updating crates.io index
Removing ahash v0.7.7
Updating config v0.13.3 -> v0.14.0
Adding const-random v0.1.17
Adding const-random-macro v0.1.16
Adding convert_case v0.6.0
Adding crunchy v0.2.2
Updating dlv-list v0.3.0 -> v0.5.2
Adding hashbrown v0.13.2
Updating ordered-multimap v0.4.3 -> v0.6.0
Updating ron v0.7.1 -> v0.8.1
Updating rust-ini v0.18.0 -> v0.19.0
Adding tiny-keccak v2.0.2
Removing toml v0.5.11
$ cargo update serde
Updating crates.io index
Updating serde v1.0.192 -> v1.0.193
Updating serde_derive v1.0.192 -> v1.0.193
$ cargo update h2
Updating crates.io index
Updating h2 v0.3.21 -> v0.3.24
Removing hashbrown v0.12.3 …
```
> Udate dependencies

- .github/workflows/coverage.yaml
Use stable rust for coverage report.
> Use stable rust for coverage report

- project-words.txt
- src/console/commands/mod.rs
- src/console/commands/seeder/api.rs
- src/console/commands/seeder/app.rs
- src/console/commands/seeder/logging.rs
- src/console/commands/seeder/mod.rs
- src/console/cronjobs/mod.rs
- src/console/mod.rs
- src/lib.rs
- src/web/api/mod.rs
Improve docs for the `seeder` command. Explain how to generate the same torrent manually if you want to double-check.
> Improve docs for `seeder` command

- project-words.txt
- src/lib.rs
Since we are using native TLS support you need to install `libssl-dev` on Linux:
```console
sudo apt-get install libssl-dev
```
> Update docs: system package dep `libssl-dev` needed on lImnux

- src/services/about.rs
- src/web/api/server/v1/contexts/about/mod.rs
- src/web/api/server/v1/routes.rs
When the API is istalled using a subfolder links don't work.
For exmaple:
https://index.torrust-demo.com/api/
License links goes to:
https://index.torrust-demo.com/v1/about/license
instead of:
https://index.torrust-demo.com/api/v1/about/license
This change uses relative URLs and also an explicit redirecting to the abnout pages, intead of showing the same content for other pages like
- https://index.torrust-demo.com/api/
- https://index.torrust-demo.com/api/v1
- https://index.torrust-demo.com/api/v1/about/
> Fix links in API about pages with subfolder

- src/bin/health_check.rs
Add timeout to `health_check` binary.
```console
cargo run --bin health_check http://127.0.0.1:3001/health_check
```
That command now fails if it does not get a response in 5 seconds.
> Add timeout to `health_check` binary

- .github/workflows/coverage.yaml
- Cargo.lock
It fixes this error:
```
error[E0635]: unknown feature `stdsimd`
--> /home/josecelano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.6/src/lib.rs:99:42
|
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
|                                          ^^^^^^^
error[E0635]: unknown feature `stdsimd`
--> /home/josecelano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.7/src/lib.rs:33:42
|
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
|                                          ^^^^^^^
Checking bytemuck v1.14.0
For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `ahash` (lib) due to 1 …
```
> Fix: [#456] `unknown feature stdsimd` with `ahash` deppendency.

- src/config.rs
- src/services/settings.rs
- src/web/api/server/v1/contexts/settings/handlers.rs
- tests/e2e/environment.rs
- tests/e2e/web/api/v1/contexts/settings/contract.rs
These fields:
- data.tracker.token
- data.database.connect_url
- data.mail.password
- data.auth.secret_key
are replaced with asterisks. Final output:
```json
{
"log_level": "info",
"website": {
"name": "Torrust"
},
"tracker": {
"url": "udp://localhost:6969",
"mode": "Public",
"api_url": "http://localhost:1212",
"token": "***",
"token_valid_seconds": 7257600
},
"net": {
"port": 3001,
"base_url": null
},
"auth": {
"email_on_signup": "Optional",
"min_password_length": 6,
"max_password_length": 64,
"secret_key": "***"
},
"database": {
"connect_url": "***"
},
"mail": {
"email_verification_enabled": false,
"from": "example@email.com",
"reply_to": "noreply@email.com",
"username": "",
"password": "***",
"server": "",
"port": 25
},
"image_cache": {
"max_request_timeout_ms": 1000,
"capacity": …
```
> Remove secrets from settings API endpoint

- src/console/commands/seeder/api.rs
- src/console/commands/seeder/app.rs
- src/web/api/client/v1/client.rs
- src/web/api/client/v1/connection_info.rs
- src/web/api/client/v1/http.rs
- src/web/api/server/v1/routes.rs
- tests/common/client.rs
The API client does not have any timeout. The client waits indefinitely for responses. That should not be the default behaviour. It should return an error after a timeout. The users using the client should handle the timeout or any other error.
> Index API client: add timeout to requests

- src/tracker/api.rs
- src/tracker/service.rs
Ass default timeout of 5 seconds for Tracker API requests.
In the future, we could use the official Tracker API client. See https://github.com/torrust/torrust-tracker/issues/689.
However, it's also fine to use this reduced client. Because we do not need all the PAI endpoints.
> Add timeouts to Tracker API Client requests

- .github/workflows/coverage.yaml
- Cargo.lock
- Cargo.toml
- src/tracker/statistics_importer.rs
- src/web/api/server/v1/routes.rs
> Overhaul logging

- src/web/api/server/v1/contexts/category/handlers.rs
- src/web/api/server/v1/contexts/settings/handlers.rs
- src/web/api/server/v1/contexts/tag/handlers.rs
- src/web/api/server/v1/contexts/torrent/handlers.rs
- src/web/api/server/v1/contexts/user/handlers.rs
Fixes #447, some changes to the code were lost in a merge, this PR restores those changes.
> fix: [#445] refactor handlers with new user id extractor

- src/web/api/client/v1/responses.rs
- src/web/api/server/v1/contexts/torrent/errors.rs
- src/web/api/server/v1/contexts/torrent/handlers.rs
- tests/common/responses.rs
Relates to: https://github.com/torrust/torrust-index-gui/issues/483
Some users are having problems uploading torrents becuase the client (browser or other clients) use the HTTP header Contetnt-Type:
`application/octet-stream`
instead of:
`application/x-bittorrent`
It seems that the reason is they don't have any application associated to that extension. So it uses the generic binary file mime type.
The MIME type can be inferred from the file extension. If the system or application uploading the file has a specific association for .torrent files, it might set the MIME type to application/x-bittorrent. In the absence of such an association, it might fall back to the generic application/octet-stream.
> Allow upload torrent with `application/octet-stream` HTTP header Content-Type

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/config.rs
- src/errors.rs
- src/models/response.rs
- src/models/torrent_file.rs
- src/services/torrent.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
```
1. Tracker running in `Public` or `Whitelisted` mode. 
Downloaded torrents should never include any tracker key.
3. Tracker running in `Private` or `PrivateListed` mode.
2.1 Guest user. 
Downloaded torrents should never include any tracker key.
2.2 Authenticated user
2.2.1 Index can get the tracker user's key (from the Index database or generate new ones).
- We should include the user's tracker key.
- We should change the download torrent button label from `download torrent` to `download private torrent` (this is an Idex GUI issue).
2.2.2 The user's tracker key is expired and the tracker API is unavailable (can't generate a new one).
Return a `503 Service Unavailable` response with the text `Can't generate user's tracker key`.
```
- Rename de download torrent button from `download …
> Overhaul tracker keys in torrents and magnet links

- src/models/category.rs
- src/models/response.rs
- src/web/api/client/v1/contexts/torrent/responses.rs
- src/web/api/server/v1/contexts/category/handlers.rs
- src/web/api/server/v1/contexts/category/responses.rs
- tests/common/contexts/torrent/asserts.rs
- tests/common/contexts/torrent/responses.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
Decouple database struct from API response for `Category`. Changes in the database schema should not affect the API contract.
> Decouple database strcut from API response for `Category`

- src/errors.rs
- src/models/user.rs
- src/services/user.rs
Usernames will only allow the following characters:
- Uppercase and lowercase letters (`A-Z`, `a-z`)
- Digits (`0-9`)
- The simple dash (`-`)
- The underscore (`_`)
Additionally, we'll enforce a maximum length of 20 characters for the usernames.
We exclude emojis, blank spaces, non-valid UTF-8 characters, and non-ASCII characters
```regex
^[A-Za-z0-9-_]{1,20}$
```
Explanation:
- `^` asserts the start of the string.
- `[A-Za-z0-9-]` is a character class that matches uppercase letters (`A-Z`), lowercase letters (`a-z`), digits (`0-9`), and the simple dash (`-`) or underscore (`_`).
- `{1,20}` quantifier makes sure that the preceding character class matches between 1 and 20 times, inclusive, which enforces your maximum length requirement.
- `$` asserts the end of the string.
This regular …
> Add more contrains for usernames

- .gitignore
- src/bin/create_test_torrent.rs
You can execute it with:
```
cargo run --bin create_test_torrent ./output/test/torrents
```
All fields are always the same except for the content and hashes. 
```json
{
"announce-list": [
[
"https://tracker.torrust-demo.com/announce"
]
],
"httpseeds": [
"https://seeder.torrust-demo.com/seed"
],
"info": {
"length": 37,
"name": "file-e1fdbe05-4d33-4748-bab0-6abd297f5230.txt",
"path": [
"file-e1fdbe05-4d33-4748-bab0-6abd297f5230.txt"
],
"piece length": 16384,
"pieces": "<hex>AA 2C 11 CB 66 F4 CE D8 CA AA 09 2C 40 AC EA BC 95 34 44 F8</hex>"
},
"nodes": [
[
"99.236.6.144",
6881
],
[
"91.109.195.156",
1996
]
]
}
```
Output dir must exist.
> New feature: a new console command to create random test torrents

- migrations/mysql/20240304104106_torrust_add_http_seeds_to_torrent.sql
- migrations/sqlite3/20240304104106_torrust_add_http_seeds_to_torrent.sql
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/models/torrent_file.rs
The field `httpseeds` was included in the `Torrent` struct but not persisted into or loaded from database.
> BEP 17. Persist metainfo field `httpseeds`

- src/bin/create_test_torrent.rs
Add `announce` field to test torrent.
With the command:
```
cargo run --bin create_test_torrent ./output/test/torrents
```
You can generate a test torrent. Currently, it does now add all the optional fields. We are adding them when we need them.
> Add `announce` field to test torrent

- migrations/mysql/20240304165035_torrust_add_nodes_to_torrent.sql
- migrations/sqlite3/20240304165035_torrust_add_nodes_to_torrent.sql
- share/default/config/index.development.sqlite3.toml
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/models/torrent_file.rs
The field `nodes` was included in the `Torrent` struct but not persisted into or loaded from the database.
> BEP 5. Persist metainfo field `nodes`

- migrations/mysql/20240305110750_torrust_bep_rename_root_hash_to_is_bep_30.sql
- migrations/mysql/20240305120015_torrust_add_independent_root_hash_field.sql
- migrations/sqlite3/20240305110750_torrust_bep_rename_root_hash_to_is_bep_30.sql
- migrations/sqlite3/20240305120015_torrust_add_independent_root_hash_field.sql
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/models/torrent_file.rs
- src/services/torrent_file.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
- tests/upgrades/from_v1_0_0_to_v2_0_0/transferrer_testers/torrent_transferrer_tester.rs
Refactor BEP 30 implementation to make it clearer and simplify implementation.
BEP 30: https://www.bittorrent.org/beps/bep_0030.html
> Refactor BEP 30 implmentation

- src/services/torrent.rs
- src/web/api/server/v1/contexts/torrent/responses.rs
- tests/common/contexts/torrent/responses.rs
- tests/e2e/web/api/v1/contexts/torrent/contract.rs
- tests/e2e/web/api/v1/contexts/torrent/steps.rs
To match the latest changes in the database. 
From:
```json
{
"data": {
"torrent_id": 12,
"info_hash": "c01f910ff0cc2a1b8c7a1f6ab948377604d8c464",
"original_info_hash": "dc0c6be689b28696319263ef27f9df4da8ded0a2"
}
}
```
To:
```
{
"data": {
"torrent_id": 12,
"canonical_info_hash": "c01f910ff0cc2a1b8c7a1f6ab948377604d8c464",
"info_hash": "dc0c6be689b28696319263ef27f9df4da8ded0a2"
}
}
```
> Refactor: rename fields in upload torrent response

- migrations/mysql/20240312130530_torrust_add_update_data_to_tracker_stats.sql
- migrations/sqlite3/20240312130530_torrust_add_update_data_to_tracker_stats.sql
- src/console/cronjobs/tracker_statistics_importer.rs
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/tracker/api.rs
- src/tracker/service.rs
- src/tracker/statistics_importer.rs
- src/utils/clock.rs
Currently, the Index imports statistics for all torrents every hour (1 hour is the default value in the configuration). We need to import stats for all torrents because we allow users to sort torrents by torrent stats (number of seeders and leechers). This PR improves a little bit the process.
**Pros:**
- With millions of torrents we don't need to load all of them into memory.
- The new field `updated_at` helps to monitor the importation process.
- We get torrent stats for 50 torrents in one request instead of one request per torrent.
**Cons:**
- Every 100 milliseconds we run a query to check which torrent stats are pending to update.
> Improve tracker statistics importation

- src/console/cronjobs/tracker_statistics_importer.rs
We are having problems with the live demo server. See:
https://github.com/torrust/torrust-demo/issues/1
Due to a high CPU and memory usage.
This increases the tracker stats importer execution interval from 100 milliseconds to 2000 milliseconds.
> Increase the tracker stats importer exec interval

- Cargo.lock
```output
Updating crates.io index
Locking 59 packages to latest compatible versions
Updating allocator-api2 v0.2.16 -> v0.2.18
Updating anyhow v1.0.81 -> v1.0.82
Updating async-compression v0.4.7 -> v0.4.8
Updating async-trait v0.1.79 -> v0.1.80
Updating brotli v3.5.0 -> v4.0.0 (latest: v5.0.0)
Updating brotli-decompressor v2.5.1 -> v3.0.0 (latest: v4.0.0)
Updating bumpalo v3.15.4 -> v3.16.0
Updating cc v1.0.90 -> v1.0.95
Updating chrono v0.4.37 -> v0.4.38
Updating crc v3.0.1 -> v3.2.1
Updating der v0.7.8 -> v0.7.9
Updating either v1.10.0 -> v1.11.0
Updating encoding_rs v0.8.33 -> v0.8.34
Updating getrandom v0.2.12 -> v0.2.14
Updating h2 v0.4.3 -> v0.4.4
Updating hostname v0.3.1 -> v0.4.0
Updating hyper v1.2.0 -> v1.3.1
Updating jobserver v0.1.28 -> v0.1.31
Updating lettre v0.11.6 -> …
```
> Udpate dependencies

- src/config.rs
- src/config/mod.rs
- src/config/v1/api.rs
- src/config/v1/auth.rs
- src/config/v1/database.rs
- src/config/v1/image_cache.rs
- src/config/v1/mail.rs
- src/config/v1/mod.rs
- src/config/v1/net.rs
- src/config/v1/tracker.rs
- src/config/v1/tracker_statistics_importer.rs
- src/config/v1/website.rs
- src/console/commands/tracker_statistics_importer/app.rs
Configuration overhaul: clean and reorganize before migration to figment.
TrackerMode enum names and serialized values can not be changed now because that's a breaking change for the toml config file and also for the API (some endpoints return the tracker mode.
They should be changed in the future:
Enum variants (Index -> Tracker):
- `Public`             -> `Public`
- `Private`            -> `Private`
- `Whitelisted`        -> `Listed` 
- `PrivateWhitelisted` -> `PrivateListed`
Enum serialized values (Index -> Tracker):
- `Public`             -> `public`
- `Private`            -> `private`
- `Whitelisted`        -> `listed` 
- `PrivateWhitelisted` -> `private_listed`
> Configuration overhaul: clean and reorganize before migration to figment

- src/console/commands/tracker_statistics_importer/app.rs
- src/lib.rs
- src/upgrades/from_v1_0_0_to_v2_0_0/upgrader.rs
- src/utils/parse_torrent.rs
- tests/e2e/mod.rs
The new Clippy version forces you to use indentation and also use the `>` marker in a multiline paragraph. For example:
**Not valid** because of the missing markers `>` and the indentation:
```
//! > **NOTICE**: The server must be running before running the tests. The
//! server url is hardcoded to `http://localhost:3001` for now. We are planning
//! to make it configurable in the future via a environment variable.
//!
```
**Valid**:
```
//! > **NOTICE**: The server must be running before running the tests. The
//! > server url is hardcoded to `http://localhost:3001` for now. We are planning
//! > to make it configurable in the future via a environment variable.
//!
```
> Fix new linting errors

- share/default/config/index.container.mysql.toml
- share/default/config/index.container.sqlite3.toml
- share/default/config/index.development.sqlite3.toml
- share/default/config/index.e2e.container.mysql.toml
- share/default/config/index.e2e.container.sqlite3.toml
- src/config/v1/api.rs
- src/config/v1/auth.rs
- src/config/v1/database.rs
- src/config/v1/image_cache.rs
- src/config/v1/mail.rs
- src/config/v1/mod.rs
- src/config/v1/net.rs
- src/config/v1/tracker.rs
- src/config/v1/tracker_statistics_importer.rs
- src/config/v1/website.rs
Configuration overhaul: define default values and remove default values from config file templates.
> Configuration overhaul: define default values and remove default values from config file templates

- src/config/mod.rs
- src/config/v1/mod.rs
You can now use the Figmenat conventions to override config values:
- `TORRUST_INDEX_CONFIG_OVERRIDE_TRACKER__TOKEN`
- `TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__SECRET_KEY`
> Remove deprecated env vars

- src/app.rs
- src/common.rs
- src/databases/database.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/errors.rs
- src/services/authentication.rs
- src/services/user.rs
- src/web/api/server/signals.rs
- src/web/api/server/v1/contexts/user/forms.rs
- src/web/api/server/v1/contexts/user/handlers.rs
- src/web/api/server/v1/contexts/user/routes.rs
- tests/common/client.rs
- tests/common/contexts/user/asserts.rs
- tests/common/contexts/user/fixtures.rs
- tests/common/contexts/user/forms.rs
- tests/e2e/web/api/v1/contexts/user/contract.rs
New API endpoint to change the users' password.
> New API endpoint to change the users' password

- Cargo.lock
- Cargo.toml
- packages/located-error/Cargo.toml
- packages/located-error/src/lib.rs
- src/bootstrap/logging.rs
- src/console/commands/seeder/api.rs
- src/console/commands/seeder/app.rs
- src/console/commands/seeder/logging.rs
- src/console/cronjobs/tracker_statistics_importer.rs
- src/databases/mysql.rs
- src/databases/sqlite.rs
- src/mailer.rs
- src/models/torrent_file.rs
- src/services/torrent.rs
- src/services/user.rs
- src/tracker/service.rs
- src/tracker/statistics_importer.rs
- src/web/api/server/mod.rs
- src/web/api/server/signals.rs
- src/web/api/server/v1/contexts/torrent/handlers.rs
- tests/environments/app_starter.rs
Move from `log` to `tracing` crate.
Old output:
```output
$ cargo run
Compiling torrust-index v3.0.0-alpha.3-develop (/home/josecelano/Documents/github/committer/me/torrust/torrust-index)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 12.31s
Running `target/debug/torrust-index`
Loading configuration from default configuration file: `./share/default/config/index.development.sqlite3.toml` ...
2024-06-07T15:35:08.192302724+01:00 [torrust_index::bootstrap::logging][INFO] logging initialized.
2024-06-07T15:35:08.252784599+01:00 [torrust_index::web::api::server][INFO] TLS not enabled
2024-06-07T15:35:08.252892290+01:00 [torrust_index::console::cronjobs::tracker_statistics_importer][INFO] Tracker statistics importer launcher started
2024-06-07T15:35:08.252979221+01:00 …
```
> Move from `log` to `tracing` crate

- share/default/config/index.container.mysql.toml
- share/default/config/index.container.sqlite3.toml
- share/default/config/index.development.sqlite3.toml
- share/default/config/index.private.e2e.container.sqlite3.toml
- share/default/config/index.public.e2e.container.mysql.toml
- share/default/config/index.public.e2e.container.sqlite3.toml
- src/app.rs
- src/bootstrap/logging.rs
- src/config/mod.rs
- src/config/v1/api.rs
- src/config/v1/auth.rs
- src/config/v1/image_cache.rs
- src/config/v1/logging.rs
- src/config/v1/mail.rs
- src/config/v1/mod.rs
- src/config/v1/net.rs
- src/config/v1/tracker.rs
- src/config/v1/tracker_statistics_importer.rs
- src/console/commands/tracker_statistics_importer/app.rs
- src/lib.rs
- src/mailer.rs
- src/services/user.rs
- src/web/api/client/v1/contexts/settings/mod.rs
- src/web/api/mod.rs
- src/web/api/server/mod.rs
- src/web/api/server/v1/contexts/settings/mod.rs
- src/web/api/server/v1/contexts/user/mod.rs
- tests/common/contexts/settings/mod.rs
- tests/e2e/environment.rs
- tests/environments/isolated.rs
A set of breaking changes in the TOML config file to improve readability and validation.
- We are normalizing all variants in enums to lowercase in TOML files.
- The option `base_url` (section `net`) already exists in the current version. It's not changed in the new version. It's optional. If it's not present it uses the request headers to get the current host.
```toml
log_level = "info"
[website]
name = "Torrust"
[tracker]
api_url = "http://localhost:1212"
mode = "Public"
token = "MyAccessToken"
token_valid_seconds = 7257600
url = "udp://localhost:6969"
[net]
port = 3001
#[net.tsl]
#ssl_cert_path = "./storage/index/lib/tls/localhost.crt"
#ssl_key_path = "./storage/index/lib/tls/localhost.key"
[auth]
email_on_signup = "Optional"
max_password_length = 64
min_password_length = 6
secret_key …
```
> Configuration overhaul: version 2 for the configuration toml file (breaking changes)

- share/default/config/tracker.private.e2e.container.sqlite3.toml
- share/default/config/tracker.public.e2e.container.sqlite3.toml
- src/config/mod.rs
- src/config/v1/tracker.rs
New breaking changes have been applied to the Tracker configuration.
- Renamed `log_level` to  `threshold`.
- Tracker mode split into `listed` and `private` flags.
- Added configuration `version`.
From:
```toml
[logging]
log_level = "info"
[core]
mode = "public"
tracker_usage_statistics = true
inactive_peer_cleanup_interval = 600
```
To:
```toml
version = "2"
[logging]
threshold = "info"
[core]
inactive_peer_cleanup_interval = 600
listed = false
private = false
tracker_usage_statistics = true
```
> Udpate tracker configuration

- src/app.rs
- src/bootstrap/logging.rs
- src/config/mod.rs
- src/config/v2/mod.rs
- src/console/commands/seeder/logging.rs
When the app is started, it prints the final configuration to the console in JSON.
**NOTICE:** Secrets are hidden.
> Configuration overhaul: print the final configuration to console

- share/default/config/index.container.mysql.toml
- share/default/config/index.container.sqlite3.toml
- share/default/config/index.development.sqlite3.toml
- share/default/config/index.private.e2e.container.sqlite3.toml
- share/default/config/index.public.e2e.container.mysql.toml
- share/default/config/index.public.e2e.container.sqlite3.toml
- src/app.rs
- src/bootstrap/logging.rs
- src/config/mod.rs
- src/config/v2/logging.rs
- src/console/commands/tracker_statistics_importer/app.rs
- tests/common/contexts/settings/mod.rs
- tests/environments/isolated.rs
Rename `log_level` to `threshold`:
```toml
[logging]
log_level = "info"
```
```toml
[logging]
threshold = "info"
```
> Configuration overhaul: rename `log_level` to `threshold`

- share/default/config/index.private.e2e.container.sqlite3.toml
- src/config/mod.rs
- src/config/v2/tracker.rs
- src/lib.rs
- src/services/torrent.rs
- src/web/api/client/v1/contexts/settings/mod.rs
- tests/common/contexts/settings/mod.rs
- tests/common/contexts/settings/responses.rs
- tests/e2e/environment.rs
- tests/e2e/web/api/v1/contexts/settings/contract.rs
Update the tracker configuration section to follow [changes in the tracker configuration](https://github.com/torrust/torrust-tracker/issues/932).
```toml
[tracker]
mode = "public"
```
```toml
[tracker]
private = false
listed = false
```
**NOTICE**: This introduces a breaking change in the Tracker API. The Index GUI must be updated. It will open a new issue in the Index GUI repo and update it today.
> Configuration overhaul: split `TrackerMode`into two flags `private` and `listed`

- share/default/config/index.container.mysql.toml
- share/default/config/index.container.sqlite3.toml
- share/default/config/index.development.sqlite3.toml
- share/default/config/index.private.e2e.container.sqlite3.toml
- share/default/config/index.public.e2e.container.mysql.toml
- share/default/config/index.public.e2e.container.sqlite3.toml
- src/config/mod.rs
- src/config/v2/auth.rs
- src/config/v2/mail.rs
- src/config/v2/mod.rs
- src/config/v2/registration.rs
- src/lib.rs
- src/services/authentication.rs
- src/services/settings.rs
- src/services/user.rs
- src/web/api/client/v1/contexts/settings/mod.rs
- src/web/api/server/v1/contexts/settings/mod.rs
- src/web/api/server/v1/contexts/user/mod.rs
- tests/common/contexts/settings/mod.rs
- tests/e2e/web/api/v1/contexts/settings/contract.rs
- tests/environments/isolated.rs
Refactor configuration for options related to email in the registration.
```toml
[auth]
email_on_signup = "optional"
[mail]
email_verification_enabled = false
```
Registration Disabled:
```toml
```
Registration without email option:
```toml
[registration]
```
Registration optionally including an email address:
```toml
[registration]
[registration.email]
```
Registration with  email:
```toml
[registration]
[registration.email]
required = true
```
Registration with optional email, but if email is supplied it is verified:
```toml
[registration]
[registration.email]
verified = true
```
Registration with email and email is verified:
```toml
[registration]
[registration.email]
required = true
verified = true
```
> Configuration overhaul: make mail-related configuration clearer

- contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
- tests/environments/shared.rs
This seems to fix the issue running E2E tests with MySQL on a GitHub runner, but I'm not sure. I've executed the tests twice.
> fix: [#580] E2E tests failing with MySQL

- share/default/config/index.container.mysql.toml
- share/default/config/index.container.sqlite3.toml
- share/default/config/index.development.sqlite3.toml
- share/default/config/index.private.e2e.container.sqlite3.toml
- share/default/config/index.public.e2e.container.mysql.toml
- share/default/config/index.public.e2e.container.sqlite3.toml
- src/config/mod.rs
- src/config/v2/mod.rs
- src/web/api/server/v1/contexts/settings/mod.rs
We made the same change in the Tracker.
```toml
[metadata]
app = "torrust-index"
purpose = "configuration"
schema_version = "2.0.0"
```
> Improve metadata section in configuration

- src/config/mod.rs
- src/config/v2/auth.rs
- src/config/v2/mod.rs
- src/config/v2/tracker.rs
- src/lib.rs
- src/mailer.rs
- src/services/authentication.rs
- src/services/user.rs
- src/web/api/client/v1/contexts/settings/mod.rs
- src/web/api/server/v1/contexts/settings/mod.rs
- src/web/api/server/v1/contexts/user/mod.rs
- tests/common/contexts/settings/mod.rs
- tests/e2e/environment.rs
It's used to sign the Json Web Token. `secret_key` was too generic.
> Rename config option `secret_key` to `user_claim_token_pepper`

- src/config/mod.rs
These options are now mandatory:
```toml
[metadata]
schema_version = "2.0.0"
[logging]
threshold = "info"
```
> Config overhaul: make some fields mandatory

- project-words.txt
- src/app.rs
- src/config/v2/mod.rs
- src/config/v2/unstable.rs
- src/services/authorization.rs
This is an **unstable** feature. You can overwrite casbin configuration to change permissions for roles:  guest, registered and admin.
You can do it by adding this new section to the TOML config file:
```toml
[unstable.auth.casbin]
model = """
[request_definition]
r = role, action
[policy_definition]
p = role, action
[policy_effect]
e = some(where (p.eft == allow))
[matchers]
m = r.role == p.role && r.action == p.action
"""
policy = """
admin, GetAboutPage
admin, GetLicensePage
admin, AddCategory
admin, DeleteCategory
admin, GetCategories
admin, GetImageByUrl
admin, GetSettings
admin, GetSettingsSecret
admin, GetPublicSettings
admin, AddTag
admin, DeleteTag
admin, GetTags
admin, AddTorrent
admin, GetTorrent
admin, DeleteTorrent
admin, GetTorrentInfo
admin, GenerateTorrentInfoListing …
```
> Feat: allow overwriting casbin configuration

- Cargo.lock
- src/models/torrent_file.rs
- src/services/user.rs
- src/web/api/server/mod.rs
- tests/environments/app_starter.rs
Update dependencies and fix linter errors.
```console
cargo update
Updating crates.io index
Locking 15 packages to latest compatible versions
Updating cc v1.1.7 -> v1.1.10
Updating clap v4.5.13 -> v4.5.15
Updating clap_builder v4.5.13 -> v4.5.15
Updating core-foundation-sys v0.8.6 -> v0.8.7
Updating hyper-util v0.1.6 -> v0.1.7
Updating mio v1.0.1 -> v1.0.2
Updating object v0.36.2 -> v0.36.3
Updating rgb v0.8.47 -> v0.8.48
Updating rustls-pki-types v1.7.0 -> v1.8.0
Updating serde v1.0.204 -> v1.0.206
Updating serde_derive v1.0.204 -> v1.0.206
Updating serde_json v1.0.122 -> v1.0.124
Updating syn v2.0.72 -> v2.0.74
Updating tempfile v3.11.0 -> v3.12.0
Updating xml-rs v0.8.20 -> v0.8.21
```
> Update dependencies and fix linter errors

- Cargo.lock
- Cargo.toml
I'm releasing the version `3.0.0-alpha.12` for all Tracker, Index and Index GUI packages following the [release plan](https://github.com/torrust/torrust-index/wiki/Releases).
> chore: synchronize version with tracker 3.0.0-alpha.12-develop

- src/services/proxy.rs
- src/services/torrent.rs
- src/services/user.rs
- src/web/api/server/v1/contexts/user/handlers.rs
There are several unwraps that lack error handling in the authorization logic when unwrapping the maybe_user_id variable, this PR fix that by handling the errors.
>  Fix unhandled errors on maybe_user_id unwraps in authorization logic

- src/errors.rs
- src/services/user.rs
Fix bug wrong error message for password too long error.
> Fix bug wrong error message for password too long error

- src/config/mod.rs
- src/config/v2/website.rs
- src/services/settings.rs
- tests/fixtures/default_configuration.toml
We need to pass legal texts to the frontent but we don't have a proper CMS. For now, we have just added the texts in the configuration to make it possible for users to overrride them. These are the new values in the config:
```toml
[website.demo]
warning = "⚠️ Please be aware: This demo resets all data weekly. Torrents not complying with our Usage Policies will be removed immediately without notice. We encourage the responsible use of this software in compliance with all legal requirements."
[website.terms]
[website.terms.upload]
content_upload_agreement = """I confirm that the content I am uploading is authorized, and I have read and agree to the terms."""
[website.terms.page]
title = "Usage Policies and Content Restrictions"
content = """
Our software is designed to support the …
```
> Add CMS content for legal texts to configuration

- .github/workflows/e2e.yaml
- .github/workflows/testing.yaml
Integration tests with MySQL are working locally but not in the GitHub Runner. We don't know why yet. See https://github.com/torrust/torrust-index/issues/580.
That's affecting deployments and releases. We move the execution to a new temporary workflow until it's fixed. Be sure to execute it locally before opening a new PR:
```console
./contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
```
> Move testing with MySQL to a new workflow
